#include "ConfigParser.hpp"
#include "ServerManager.hpp"
#include <iostream>

int main(int argc, char **argv) {
    ConfigParser parser;
	const std::vector<ServerConfig>& servers =  parser.parse();
	ServerManager serverManager(servers);

    return 0;
}

/*
1. Instantiate the ConfigParser and call parse() to generate the 
std::vector<ServerConfig>.  

2. Add a setter method 
(e.g., void setServers(const std::vector<ServerConfig>& servers)) 
or a parameterized constructor to ServerManager.  

3. Pass the vector generated by the parser into the ServerManager 
instance before calling ServerManager::initServers(). */