# webserv.conf

server {
    listen 8080;
    server_name localhost webserv.com;
    
    # Global settings for this specific server
    client_max_body_size 10M;
    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    # Default route
    location / {
        root /var/www/html;
        index index.html index.htm;
        allow_methods GET POST;
        autoindex on;
    }

    # Route specifically for uploading files
    location /uploads {
        root /var/www/uploads;
        allow_methods POST DELETE;
        upload_store /var/www/uploads/tmp;
    }

    # Route for executing CGI scripts
    location /cgi-bin {
        root /var/www/cgi-bin;
        allow_methods GET POST;
        cgi_ext .py .php;
        cgi_path /usr/bin/python3 /usr/bin/php-cgi;
    }

	# Route specifically for redirection
	location /old-page {
        return 301 /new-page.html;
    }
}

# You can define multiple servers running on different ports
server {
    listen 9090;
    server_name test.local;
    
    location / {
        root /var/www/test;
        index test.html;
        allow_methods GET;
    }
}